### ISSUE TITLE
Add backtracking to solve_monotonic

### ISSUE THREAD

**Issue by jeremie-koenig** [CertiKOS/coqrel#2]
When `Monotonicity` picks the wrong relational property and `solve_monotonic` fails at a later point, it should be able to go back and try the next instance of `Monotonicity` (which will use the next relational property available). To achieve that we could reify the tactic into a `SolveMonotonic` typeclass. Some of the cases of the master `match` may bit slightly tricky to handle. Perhaps if I get the stuff in `Delay.v` to work that might help.

With Coq 8.5 there might be some alternative strategies but I'm not sure whether we want to upgrade just yet.

**Comment by gmalecha** [comment]
In 8.5 you can use the + combinator to do this, e.g. `(apply X + apply Y); foo` acts similar to `first [ apply X ; foo | apply Y ; foo ]`. In 8.4, the usual way to do this is to code tactics in continuation passing style, e.g. `first [ apply X ; k | apply Y ; k ]` and usually `k` ends with a `solve`.

**Comment by jeremie-koenig** [comment]
Thanks for the tips!

One specific difficulty I have is, I need to interface with the backtracking in `typeclasses eauto`, so that instead of multiple tactics (`foo + bar`), I want to try all possible typeclass instances that match (say) `Proper _ plus`. It would be great if 8.5 unifies the backtracking in `eauto` (trying different hints) and Ltac (trying different branches of +), but I doubt that's the case. I should investigate.

**Comment by gmalecha** [comment]
8.5 does not unify backtracking in `eauto` with other features of Ltac. However, you should be able to use my [with-hint-db plugin](https://github.com/gmalecha/coq-with-hint-db) to do this. Essentially you should be able to say something like:

```
plus_of [ typeclass_instances ] run (fun x => apply x); ....
```

and get the backtracking search that you are looking for. `plus_of` only works in 8.5 because + only works in 8.5 but you might be able to use the 8.4 version if you code the tactic in CPS.

**Comment by jeremie-koenig** [comment]
That plugin seems quite interesting!

**Comment by gmalecha** [comment]
It is still under development so if there are features that would be useful then please post issues in the issue tracker.

**Comment by gmalecha** [comment]
I should mention that the plugin has moved: https://github.com/gmalecha/coq-ltac-iter
and it is now available via opam: `opam install coq-ltac-iter`

**Comment by jeremie-koenig** [comment]
Backtracking is now implemented in the `rauto` tactic.

(As planned, I fixed `Delay.v` and used a typeclass reification of the components of the old `solve_monotonic`.)
