### ISSUE TITLE
Decide on a LICENSE for future releases

### ISSUE THREAD

**Issue by jwiegley** [CertiKOS/coqrel#5]
Hello, I'm interested in using `coqrel` in a development I'm working on, but I need to know the license what you are using specifically.

I had developed my own scheme for doing these relations separately, but once I found how far along you'd gotten, it seemed only natural to switch over to this one. Nice work!

**Comment by jeremie-koenig** [comment]
Hi John, thanks for your interest in `coqrel`!

We've decided to distribute the current prototype under an MIT license. We may end up choosing a different open-source license when we do an official release. (Please feel free to weigh in!)

Incidentally, as you can see the code itself is still in its infancy and some interfaces will very likely change. (Please feel free to weigh in!)

I hope you find it useful nonetheless, let me know if you have any other issues.

**Comment by jwiegley** [comment]
Thank you, Jérémie! I have already begun using `coqrel`, and it has replaced the work I did previously quite effectively.  I'll let you know as any ideas or issues arise. :)  Thanks again.
